name: Run Dockerized ETL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-docker-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (optional, if pushing to Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#added comment for new push##
      - name: Build Docker image
        run: docker build -t load-data-app .

      - name: Run Docker container
        run: docker run --rm load-data-app